cd /home/jm/Examples/_UNSORTED_/

function bbbb(){
    git clone -- 'https://github.com/kaergel/docker-vdirsyncer' kaergel_docker-vdirsyncer
git clone -- 'https://github.com/RipMeApp/ripme' RipMeApp_ripme
git clone -- 'https://github.com/rickyrockrat/parcellite' rickyrockrat_parcellite
git clone -- 'https://github.com/pimutils/vdirsyncer' pimutils_vdirsyncer
git clone -- 'https://github.com/Corwind/termite-install' Corwind_termite-install
git clone -- 'https://github.com/thestinger/termite' thestinger_termite
git clone -- 'https://github.com/easymodo/qimgv' easymodo_qimgv
git clone -- 'https://github.com/yarnpkg/rfcs' yarnpkg_rfcs
git clone -- 'https://github.com/divoxx/do.bash' divoxx_do.bash
git clone -- 'https://github.com/rjshanahan/twitter_scraper' rjshanahan_twitter_scraper
git clone -- 'https://github.com/sebinsua/scrape-twitter' sebinsua_scrape-twitter
git clone -- 'https://github.com/meetmangukiya/instagram-scraper' meetmangukiya_instagram-scraper
git clone -- 'https://github.com/jonbakerfish/TweetScraper' jonbakerfish_TweetScraper
git clone -- 'https://github.com/hiikezoe/web-ext-webpack-plugin' hiikezoe_web-ext-webpack-plugin
git clone -- 'https://github.com/jpavon/react-scripts-ts' jpavon_react-scripts-ts
git clone -- 'https://github.com/excaliburjs/example-ts-webpack' excaliburjs_example-ts-webpack
git clone -- 'https://github.com/YDJ-FE/ts-react-webpack' YDJ-FE_ts-react-webpack
git clone -- 'https://github.com/TypeStrong/fork-ts-checker-webpack-plugin' TypeStrong_fork-ts-checker-webpack-plugin
git clone -- 'https://github.com/bisguzar/twitter-scraper' bisguzar_twitter-scraper
git clone -- 'https://github.com/parkhom001/TwitterDataScraper' parkhom001_TwitterDataScraper
git clone -- 'https://github.com/NandanDesai/TwitterScraper4J' NandanDesai_TwitterScraper4J
git clone -- 'https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader' rubenspgcavalcante_webpack-chrome-extension-reloader
git clone -- 'https://github.com/stefanwille/blueprintjs-with-react' stefanwille_blueprintjs-with-react
git clone -- 'https://github.com/motdotla/dotenv' motdotla_dotenv
git clone -- 'https://github.com/ritwickdey/live-server-web-extension' ritwickdey_live-server-web-extension
git clone -- 'https://github.com/Azure/azure-webjobs-sdk-extensions' Azure_azure-webjobs-sdk-extensions
git clone -- 'https://github.com/schovi/create-chrome-extension' schovi_create-chrome-extension
git clone -- 'https://github.com/schovi/webpack-chrome-extension' schovi_webpack-chrome-extension
git clone -- 'https://github.com/sencha-extjs-examples/PWA' sencha-extjs-examples_PWA
git clone -- 'https://github.com/WebMemex/webmemex-extension' WebMemex_webmemex-extension
git clone -- 'https://github.com/web-ext-labs/ui-tool' web-ext-labs_ui-tool
git clone -- 'https://github.com/liady/webpack-node-externals' liady_webpack-node-externals
git clone -- 'https://github.com/nebulasio/WebExtensionWallet' nebulasio_WebExtensionWallet
git clone -- 'https://github.com/martinsbalodis/web-scraper-chrome-extension' martinsbalodis_web-scraper-chrome-extension
git clone -- 'https://github.com/sixohsix/twitter' sixohsix_twitter
git clone -- 'https://github.com/twintproject/twint' twintproject_twint
git clone -- 'https://github.com/bear/python-twitter' bear_python-twitter
git clone -- 'https://github.com/ttezel/twit' ttezel_twit
git clone -- 'https://github.com/jakubroztocil/httpie' jakubroztocil_httpie
git clone -- 'https://github.com/microsoft/TypeScript-Node-Starter' microsoft_TypeScript-Node-Starter
git clone -- 'https://github.com/bower/bower' bower_bower
git clone -- 'https://github.com/yarnpkg/yarn' yarnpkg_yarn
git clone -- 'https://github.com/publik-void/config-kitty' publik-void_config-kitty
git clone -- 'https://github.com/MegaBluejay/config-kitty' MegaBluejay_config-kitty
git clone -- 'https://github.com/Microsoft/TypeScript' Microsoft_TypeScript
git clone -- 'https://github.com/Microsoft/TypeScript-Handbook' Microsoft_TypeScript-Handbook
git clone -- 'https://github.com/microsoft/TypeScript' microsoft_TypeScript
git clone -- 'https://github.com/angelozerr/tsserver-plugins' angelozerr_tsserver-plugins
git clone -- 'https://github.com/neoclide/coc-tsserver' neoclide_coc-tsserver
git clone -- 'https://github.com/jwilm/alacritty' jwilm_alacritty
git clone -- 'https://github.com/kovidgoyal/kitty' kovidgoyal_kitty
git clone -- 'https://github.com/lerna/lerna' lerna_lerna
git clone -- 'https://github.com/daniellienert/dl-gallery-map' daniellienert_dl-gallery-map
git clone -- 'https://github.com/daniellienert/DL.Gallery' daniellienert_DL.Gallery
git clone -- 'https://github.com/mikf/gallery-dl' mikf_gallery-dl
git clone -- 'https://github.com/ripmeapp/ripme' ripmeapp_ripme
git clone -- 'https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c' lukechilds_a83e1d7127b78fef38c2914c4ececc3c
git clone -- 'https://help.github.com/en/articles' en_articles
git clone -- 'https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8' steinwaywhw_a4cd19cda655b8249d908261a62687f8
git clone -- 'https://github.com/webpack/enhanced-resolve' webpack_enhanced-resolve
git clone -- 'https://github.com/clarkbw/jest-webextension-mock' clarkbw_jest-webextension-mock
git clone -- 'https://github.com/cypress-io/cypress' cypress-io_cypress
git clone -- 'https://github.com/balena-io/etcher' balena-io_etcher
git clone -- 'https://github.com/fregante/Awesome-WebExtensions' fregante_Awesome-WebExtensions
}; bbbb
